language: python
sudo: required
group: deprecated-2017Q3
python:
  - "2.7"

#cache:
#  directories:
#    - $HOME/.cache/pip

install:
  - travis_retry pip install -q -r requirements.txt

script:
  - coverage run --source uhppote_rfid test
